
#kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
#kafka.value.serializer=com.js.trade.kafka.kryo.KryoSerializer
#kafka.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#kafka.value.deserializer=com.js.trade.kafka.kryo.KryoDeserializer

########## global configs of match ##########
com.nxquant.exchange.match.global.pollTimeout=10000
com.nxquant.exchange.match.global.inputTopic=MATCH
com.nxquant.exchange.match.global.snapTopic=MATCH-SS
com.nxquant.exchange.match.global.incTopic=MATCH-SS-INCREMENT


########## input of consumer ##########
com.nxquant.exchange.match.input.consumer.session.timeout.ms=30000
com.nxquant.exchange.match.input.consumer.max.poll.records=1000
com.nxquant.exchange.match.input.consumer.max.poll.interval.ms=100000
com.nxquant.exchange.match.input.consumer.heartbeat.interval.ms=10000
com.nxquant.exchange.match.input.consumer.group.id=input.consumer
com.nxquant.exchange.match.input.consumer.auto.offset.reset=earliest
com.nxquant.exchange.match.input.consumer.isolation.level=read_committed
com.nxquant.exchange.match.input.consumer.enable.auto.commit=false
com.nxquant.exchange.match.input.consumer.bootstrap.servers=127.0.0.1:9091
com.nxquant.exchange.match.input.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
com.nxquant.exchange.match.input.consumer.value.deserializer=com.nxquant.exchange.base.core.kryo.KryoDeserializer


########## snap of consumer ##########
com.nxquant.exchange.match.snap.consumer.session.timeout.ms=30000
com.nxquant.exchange.match.snap.consumer.max.poll.records=1000
com.nxquant.exchange.match.snap.consumer.max.poll.interval.ms=100000
com.nxquant.exchange.match.snap.consumer.heartbeat.interval.ms=10000
com.nxquant.exchange.match.snap.consumer.group.id=snap.consumer
com.nxquant.exchange.match.snap.consumer.auto.offset.reset=none
com.nxquant.exchange.match.snap.consumer.isolation.level=read_committed
com.nxquant.exchange.match.snap.consumer.enable.auto.commit=false
com.nxquant.exchange.match.snap.consumer.bootstrap.servers=127.0.0.1:9091
com.nxquant.exchange.match.snap.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
com.nxquant.exchange.match.snap.consumer.value.deserializer=com.nxquant.exchange.base.core.kryo.KryoDeserializer


########## inc of consumer ##########
com.nxquant.exchange.match.inc.consumer.session.timeout.ms=30000
com.nxquant.exchange.match.inc.consumer.max.poll.records=1000
com.nxquant.exchange.match.inc.consumer.max.poll.interval.ms=100000
com.nxquant.exchange.match.inc.consumer.heartbeat.interval.ms=10000
com.nxquant.exchange.match.inc.consumer.group.id=inc.consumer
com.nxquant.exchange.match.inc.consumer.auto.offset.reset=none
com.nxquant.exchange.match.inc.consumer.isolation.level=read_committed
com.nxquant.exchange.match.inc.consumer.enable.auto.commit=false
com.nxquant.exchange.match.inc.consumer.bootstrap.servers=127.0.0.1:9091
com.nxquant.exchange.match.inc.consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
com.nxquant.exchange.match.inc.consumer.value.deserializer=com.nxquant.exchange.base.core.kryo.KryoDeserializer


#web
server.port=9900
server.servlet.context-path=/
server.tomcat.uri-encoding=UTF-8
spring.web.resources.add-mappings=true